window.SIDEBAR_CONFIG = [
  {
    id: "home",
    title: "Home",
    badge: "",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>`,
    hasFullpage: false,
    init: () => window.HomeTemplate?.init?.(),
  },
  {
    id: "death",
    title: "Death Pipeline",
    badge: "LIVE",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>`,
    hasFullpage: true,
    init: () => window.DeathTemplate?.init?.(),
    loadFull: () => window.DeathTemplate?.loadFull?.(),
  },
  {
    id: "recon",
    title: "Reconnaissance",
    badge: "",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>`,
    hasFullpage: true,
    init: () => window.ReconTemplate?.init?.(),
    loadFull: () => window.ReconTemplate?.loadFull?.(),
  },
  {
    id: "analytics",
    title: "Analytics",
    badge: "",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>`,
    hasFullpage: true,
    init: () => window.AnalyticsTemplate?.init?.(),
    loadFull: () => window.AnalyticsTemplate?.loadFull?.(),
  },
  {
    id: "notes",
    title: "Notes",
    badge: "",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>`,
    hasFullpage: true,
    init: () => window.NotesTemplate?.init?.(),
    loadFull: () => window.NotesTemplate?.loadFull?.(),
  }
];
